name: template
description: A template Flutter Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  change_case: ^2.0.1
  crypto: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  flutter_screenutil: ^5.5.3+2
  formz: ^0.6.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  shared_preferences: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.3.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
