name: template
description: A template Flutter Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  change_case: ^1.0.2
  crypto: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  formz: ^0.5.0-dev.1
  freezed_annotation: ^2.1.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
